name: Build and Release Neshangar Project

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Neshangar.sln

      - name: Build the project
        run: dotnet build Neshangar.sln --configuration Release

      - name: Publish the project
        run: dotnet publish Neshangar/Neshangar.csproj -c Release -o ./bin/Publish

      - name: Create release artifact
        run: |
          $version = (Get-Item ./bin/Publish/Neshanger.exe).VersionInfo.FileVersion
          Compress-Archive -Path ./bin/Publish/* -DestinationPath ./Neshanger-v$version.zip
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Neshanger-v${{ github.ref_name }}
          path: ./Neshanger-v${{ github.ref_name }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Neshanger-v${{ github.ref_name }}
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Neshangar project"
          files: ./release/Neshanger-v${{ github.ref_name }}.zip