name: Build and Release Neshangar Project

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519
  
      - name: Clone Neshangar.Core repository
        run: git clone git@github.com:mjd132/Neshangar.Core.git ../Neshangar.Core

      - name: Restore dependencies
        run: dotnet restore Neshangar.sln

      - name: Build the project
        run: dotnet build Neshangar.sln --configuration Release

      - name: Publish the project
        run: dotnet publish ./Neshangar.csproj -c Release -o ./bin/Publish

      - name: Create and upload release artifact
        run: |
          Compress-Archive -Path ./bin/Publish/* -DestinationPath ./Neshangar-${{github.ref_name}}.zip
        shell: pwsh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Neshangar Desktop (Windows)"
          files: ./Neshangar-${{ github.ref_name }}.zip